### ISSUE TITLE
HLS Live stream starting automatically even setting autoStartLoad as false

### ISSUE THREAD

**Issue by renefs** [polimediaupv/paella-core#10]
Hi,

I'm experiencing one issue with version `1.0.2` and the HLS playback.

Turns out that, even if I set `autoStartLoad: false` on the config.json file, the stream starts automatically, but only the presentation stream, the presenter remains stopped.

package.json:
```json
  "dependencies": {
    "paella-core": "^1.0.2",
    "paella-basic-plugins": "^1.0.0",
    "paella-slide-plugins": "^1.0.0"
    }
```

Let me know if you require something else.

Cheers,
Rene

**Comment by ferserc1** [comment]
I have not been able to reproduce the bug you indicate in any HLS stream.

In any case, I can't help you without seeing the code of your player or the manifest file with the video configuration.

**Comment by renefs** [comment]
Hola Fernando,

Sure, no problem.

- data.json: https://gitlab.cern.ch/webcast/webcast-website-static/-/blob/paella7/public/manifest/test/data.json
- config.json: https://gitlab.cern.ch/webcast/webcast-website-static/-/blob/paella7/public/config/config.json
- Player code: https://gitlab.cern.ch/webcast/webcast-website-static/-/blob/paella7/src/components/Player.js

If you need to, you can clone the project, branch to `paella7`, `yarn`, `yarn startdev` and the project should run.

Gracias!

**Comment by ferserc1** [comment]
Please note that the video preview is mandatory in Paella Player 7. If the preview is not included, the behavior of the player is unpredictable:

[Video manifest documentation (data.json)](https://github.com/polimediaupv/paella-core/blob/main/doc/video_manifest.md)

> The video cataloging data is used to display the title, preview, duration and other data. In this section, the duration and preview fields are mandatory.
