### ISSUE TITLE
Paella 7 in opencast 11.x not working in Safari

### ISSUE THREAD

**Issue by kristofkeppens** [polimediaupv/paella-core#12]
We are testing paella 7 in our opencast installation cause at the moment the old paella player doesn't work in Safari. This however still seems to be the case for paella 7. I'm seeing the following notice in the javascript console 👍 

`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't._players[0].currentTimeSync')`

Every other browser I tested ( Chrome, firefox, Edge ) works fine.

**Comment by mliradelc** [comment]
Hi @kristofkeppens Here at the uni Cologne we find the same errors (We use HLS), but we found that Paella 7 is very picky in the way you codify the video. The strange part is that if we play the same stream with any other player (including the built-in player of Safari), the stream plays with any other issue.

From what I've found, if I add the low latency parameter to the video, this will be played in Paella using safari. The problem with the low latency is that it lowers your video quality. 

After many tests, it is like an issue with the UI that hangs when HLS.js is playing the video (When the debug  mode of hls.js is enabled) you can see in the logs that after the UI hangs is still running and getting the video segments. Still, I can't find the exact part where hangs in Paella. I hope that the Polimedia team can find it.

**Comment by ferserc1** [comment]
This error is fixed in paella-core 1.0.11, and updated in our (UPV) opencast fork.
