### ISSUE TITLE
Slide previews select the previous slide segment

### ISSUE THREAD

**Issue by mliradelc** [polimediaupv/paella-core#15]
Paella 7 set the timeline marks for the slides one slide before the correct one. This error begins on the second slide onwards (As it can be seen on the video attached) 

This event was also tested with Paella 6 and Theodul without any errors with the slides.

https://user-images.githubusercontent.com/8040628/149956766-f7524fe2-cdab-4067-a238-1ac092f05b77.mov

**Comment by ferserc1** [comment]
This bug is related with the paella-slide-plugins repository:
[https://github.com/polimediaupv/paella-slide-plugins/issues/2](https://github.com/polimediaupv/paella-slide-plugins/issues/2)
