### ISSUE TITLE
More than one paella player instance with enabled shortcut plugins.

### ISSUE THREAD

**Issue by renefs** [polimediaupv/paella-core#155]
Hi,

I'm implementing Paella7 in a React application and I'm getting the following warnings from `paella-core`.

```
paella-core  - Warning: Warning: more than one paella player instance with enabled shortcut plugins.
paella-core  - Warning: Check your code to ensure that only one instance of paella player registers keyboard shortcut plugins.
 ```

When the component that instantiates Paella7 I'm setting it to `null`, but it seems that some parts of the player remain:

```js
React.useEffect(() => {
  // code

  return () => { // Remove the player when the functional component unmounts
    playerRef.current = null;
  };
}, []);
```

Is there a way to avoid these warnings and remove completely the player remains when another instance is created?

Thanks.
Rene

**Comment by renefs** [comment]
After some investigation I think I found a workaround for this. Basically, it happens because when a Paella Player instance is created it is added to a list of instances (__paella_instances__) in the global window object (global.window).

It does the same for `__paella_shortcuts_player__`, which is the one causing the warning.

So my solution is the following:

```js
React.useEffect(() => {
  // code

  return () => { // Remove the player when the functional component unmounts
    playerRef.current = null;
    global.window.__paella_instances__ = null; // <- Add this line
    global.window.__paella_shortcuts_player__ = null; // <- Add this line
  };
}, []);
```
It would be nice that paella included a function itself to do the cleanup. For instance, VideoJS has a `player.disponse()` method to clean these things.

**Comment by ferserc1** [comment]
The problem here is that being a SPA application, the player instance is still active. What you are proposing here is not a good practice: these two variables are used internally and if you do this you can cause unexpected behaviors.

I'm not a great React expert, and I can't tell you exactly how to do it, but the solution is to reuse the palla instance. For that you can use the lifecycle functions and just create the instance the first time:

```js
React.useEffect(() => {
    if (!yourPlayer) {
        yourPlayer = new Paella(...);
    }
    // Load player here

    return () => {
        yourPlayer.unload();
    }
});
```

[paella-core life cycle](https://paellaplayer.upv.es/#/doc/life_cycle.md)

**Comment by renefs** [comment]
Gracias Fernando! Your comment helped me a lot and I think that I achieved a good solution.

With the following code, the warnings disappear and the player is reused by the app components. I hope it helps the people implementing it on React.

I found, however, that there is another warning now, and this one's message looks pretty clear: missing implementation on the LogEventPlugin.

```
unloadLogEventPlugins: not implemented
```

```js
export default function Player() {
  const videoRef = useRef(null);
  const playerRef = useRef(null);

  useEffect(() => {
    const loadPaella = async () => {
        let player: any;
        const initParams = {
            configUrl: "/config/config.json",
            // Your other paella configuration params
        }
        if (!playerRef.current) {
          const videoElement = videoRef.current;
          if (!videoElement) {
            return;
          }
          player = new Paella(videoRef.current, initParams);
          } else {
            player = playerRef.current;
          }

      try {
          await player.loadManifest();
          await utils.loadStyle("/config/style.css");
          playerRef.current = player;
       } catch (error) {
          console.log(error);
      }
   };

   loadPaella();

   return () => {
     if (playerRef.current) {
        console.log("Unmount -> Setting player to null");
        const player = playerRef.current as any;
        player.unload();
     }
   };
  }, []);

  if (!videoRef) {
    return <div>Loading player...</div>;
  }

  return (
    <div
      data-testid="player-container"
      ref={videoRef}
      className="player-container"
      style={{
        minHeight: "600px",
      }}
    />
  );
}

**Comment by ferserc1** [comment]
I have created a new issue to see if this warning is a message that I have not removed, or if something is really missing in the implementation: #156
