### ISSUE TITLE
[UI] Mouse hover over slides, doesn't show a preview like in Paella 6

### ISSUE THREAD

**Issue by mliradelc** [polimediaupv/paella-core#17]
In Paella 6, if you mouse hover over the slide previews, you can see a complete preview of the slide. (On the video)

https://user-images.githubusercontent.com/8040628/149969403-8f8f6370-2d21-40f5-9673-62f17963a2ca.mov

This is not in Paella 7 (On the video)

https://user-images.githubusercontent.com/8040628/149969451-7f7e7ee5-5a7e-43c1-b921-976823e84fbb.mov

**Comment by ferserc1** [comment]
This issue is related to the paella-slide-plugins plugin. It has been recreated in the correct repository:

[https://github.com/polimediaupv/paella-slide-plugins/issues/1](https://github.com/polimediaupv/paella-slide-plugins/issues/1)
