### ISSUE TITLE
Hide progress bar on live streams

### ISSUE THREAD

**Issue by renefs** [polimediaupv/paella-core#177]
Hi, I was wondering if there is a way to hide the progress bar on live streams. I think it makes sense having it on finished streams/videos, but not if they are live. Paella 6 was not displaying it and we would like to have the same behaviour. Thanks.

![screenshot-13-feb](https://user-images.githubusercontent.com/1094547/218429290-04dab717-5f82-4924-8299-08ac3b46efd1.png)

**Comment by ferserc1** [comment]
Your proposal, with some modification, could be used to implement a plugin that hides the time line bar and also shows a text indicating that it is a live event. Please review the changes I have proposed in your pull request, I think we can add a very interesting plugin.

![image](https://user-images.githubusercontent.com/7019720/227161494-9ee80dea-d139-4a10-b113-408aeefa6b75.png)

**Comment by ferserc1** [comment]
New APIs added in paella-core 1.25 to implement the live streaming indicator plugin
