### ISSUE TITLE
Paella calls to isEnabled function when plugin is not in config.json file

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella-core#187]
Example:
If your config.json file has no config for backward/forward plugins. Paella should not call isEnabled function.

Paella is calling this function causing to throw en exception and Paella fails to load.
https://github.com/polimediaupv/paella-basic-plugins/blob/0816138c5694a2ff3481e513db7612fe5a2fcf7d/src/plugins/es.upv.paella.forwardButtonPlugin.js#L22-L26

**Comment by ferserc1** [comment]
Fixed in commit [0c74292 ](https://github.com/polimediaupv/paella-core/commit/0c7429281a84ee8d175ae450ab3f2de1218af36f)
