### ISSUE TITLE
Duration and Title in manifest

### ISSUE THREAD

**Issue by gasparuben** [polimediaupv/paella-core#200]
Hi,
We have a question related to two parameters of data.json manifest:

1) About **title** metadata:

We have noticed that even if in the documentation [1] it’s not set as mandatory, I looks it’s. This is breaking some of the lectures we had displayed with no issues with paella 6.

2) About **duration** metadata:

It looks duration is also mandatory for **hls** or **hlsLive** which makes a bit less sense for live content specially because we dont know the duration before hand (we could just estimate it). This was not the case for paella-core:

Which "duration" should be set for live events e.g. hls ones? Is it really needed?

Thank you,
Ruben
[1] https://paellaplayer.upv.es/#/doc/video_manifest.md

**Comment by ferserc1** [comment]
We have decided to keep only the preview image mandatory, as it is required if the browser blocks autoplay. The rest of the metadata will no longer be mandatory in the next release, which we will publish this week.
