### ISSUE TITLE
Select video quality symbol: Fuzzy and too small

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella-core#209]
Quality button looks fuzzy and "auto" is not centered. 
Also, it's too small:
![229182767-1cc6c998-a8bd-4e07-b8d8-dcea82541d9f](https://user-images.githubusercontent.com/2735202/229723482-f79ab226-49f8-475b-8652-9a851f147dd3.png)
![229182902-fa24258a-3fbc-4981-bd55-3101ceadb9d0](https://user-images.githubusercontent.com/2735202/229723511-e1b8cb79-2c20-4967-b666-92da892982eb.png)

Maybe we can remove the icon and leave just the text. Like playbackrate plugin:
![Captura de pantalla 2023-04-04 a las 9 42 18](https://user-images.githubusercontent.com/2735202/229723810-f0162ab6-f63c-4408-88d6-59bbe16205d9.png)

Issue comes from: https://github.com/polimediaupv/paella-ethz/issues/31

**Comment by ferserc1** [comment]
This issue is related with paella-basic-plugins repository.

**Comment by miesgre** [comment]
> This issue is related with paella-basic-plugins repository.

Ok. I recreated the issue in `paella-basic-plugins` repository.
- https://github.com/polimediaupv/paella-basic-plugins/issues/3
