### ISSUE TITLE
Suggestion: Have a text to guide users to the correct repository

### ISSUE THREAD

**Issue by mliradelc** [polimediaupv/paella-core#21]
Hi, because the new paella 7 comes in several repositories, would be nice to have a note when you start to write an issue/pull request like:

> Hi, Thanks for reporting a bug/submit a pull request,
> 
> Paella 7 comes in multiple repositories, to make a better report/contribution, we ask you to go to these repositories:
> 
> - Regarding user tracking (Link A)
> - Regarding user interface (Link B)
> - Regarding playback (Link C)
> -  ...
> 
> 
> If you after reading this you are now in the correct repository, please delete this text and write your issue/contribution.
 

Thanks for your great work
Max

**Comment by polimediaupv** [comment]
We have added a repository identification guide for submitting issues, as well as instructions and a reference to the guide in the bug report templates of all repositories related to paella-core and its plugins.

[https://paellaplayer.upv.es/#/contributions](https://paellaplayer.upv.es/#/contributions)
