### ISSUE TITLE
Close sub-menus automatically when focus lost?

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella-core#298]
Tab/Keyboard control:

- When the focus leaves the a control’s sub menu, that sub-menu should automatically close

Screen Reader:

- The layout button is not hiding it’s popup menu after the menu looses focus. 
   All sub-menus should automatically hide themselves after they loose focus.
   Most (all?) are not doing that.

@karendolan

**Comment by ferserc1** [comment]
This operation is not at all clear to me. An accidental press of the tab key would close the pop up, for that reason we are not closing them.

To close a pop up, the escape key is currently configured.
