### ISSUE TITLE
Do not apply certain CSS properties to the `player-container`

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#3]
The DOM node passed to the `Paella` constructor gets assigned the `player-container` CSS class. That class defines these properties:

```css
width: 90vw;
height: 90vh;
left: 5vw;
top: 5vh;
position: relative;
font-family: helvetica, arial, sans-serif;
```

I think `position: relative` is reasonable because children of that node use absolute positioning and rely on the container having relative position. But the other properties should not be applied in my opinion:

`width`, `height`, `left` and `top` are all defined in terms of viewport units. But in most use cases, the application using Paella will decide on the width and height of the container. After all, the container is usually embedded in some other web page. So just always setting width/height to viewport units seems unhelpful. Of course, one can always override these properties, which is what we do in Tobira right now. But I think it would be better if those properties weren't there in the first place.

Similar reasoning for `font-family`: applications using Paella will usually have a design (with fonts) of their own. So they do want the font choice to also apply to the player.

**Comment by ferserc1** [comment]
You are right, these properties should only be in the stylesheets of the example code, but they are being introduced in the library.

Thanks for your contribution
