### ISSUE TITLE
Can ERROR events be subscribed to?

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella-core#305]
In Paella 6x, custom plugins could subscribe to paella.events.error, for example, for tracking/quality purposes. https://github.com/polimediaupv/paella/blob/develop/src/00_base.js#L36-L86

Is there a way to subscribe to errors in Paella7?

**Comment by karendolan** [comment]
For example, it would be helpful to be able to listen to playerState changes https://github.com/polimediaupv/paella-core/blob/main/src/js/Paella.js#L598-L602

**Comment by ferserc1** [comment]
I am preparing an update to be able to subscribe to log events.

**Comment by ferserc1** [comment]
Now you can subscribe to log message events. You can see the documentation here:
- https://paellaplayer.upv.es/#/doc/events.md
- https://paellaplayer.upv.es/#/doc/log.md
