### ISSUE TITLE
Request export PaellaCoreVideoFormats from paella-core

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella-core#327]
Request for `PaellaCoreVideoFormats` to be added to the paella-core exports so new custom video plugins can be created by adopters. https://github.com/polimediaupv/paella-core/blob/main/src/index.js

**Comment by polimediaupv** [comment]
This is already being done. See the documentation for more information:

[https://paellaplayer.upv.es/#/doc/exported_plugins.md](https://paellaplayer.upv.es/#/doc/exported_plugins.md)

**Comment by karendolan** [comment]
The actual reason I asked for this because I'm *temporarily* overriding mp4Video and hlsVideo to workaround #323. Those files needed to links their imports. I ended up writing a *temporary* local file for that import.
