### ISSUE TITLE
popup-content partially hidden on thin screeens

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella-core#334]
popup-content is hidden off screen on thin screens.

<img width="581" alt="Screenshot 2023-09-18 at 2 56 46 PM" src="https://github.com/polimediaupv/paella-core/assets/1331728/a3127027-d844-4ce8-a272-922cb4cc2a1f">

**Comment by ferserc1** [comment]
I can't replicate this bug:

<img width="686" alt="image" src="https://github.com/polimediaupv/paella-core/assets/7019720/6a13e814-ff47-4963-a2cb-cbbe2e39b045">

However, the `paella-core` version of the website was not updated until yesterday, it is possible that the bug was already fixed.
