### ISSUE TITLE
Hide UI when the cursor or focus leaves the player

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#336]
On YouTube, if your mouse leaves the player area, the UI is immediately hidden. Which I think is quite useful. [David also wished for the UI to be hidden way faster](https://github.com/elan-ev/tobira/pull/938#issuecomment-1725106418).

**Comment by ferserc1** [comment]
I think this is a good idea. Maybe it is too radical to apply this change directly, but it is possible to add a parameter so that this behavior can be configured.
