### ISSUE TITLE
Consider changing the cursor when hovering on the timeline/scrubber or buttons

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#341]
(For reference, this came up [here](https://github.com/elan-ev/tobira/issues/707))

I think it would improve UX if the cursor would change to `cursor: pointer` when hovering on the timeline/scrubber or on any of the buttons. This indicates to the user that they are over an area that they can interact with. Keeping the default cursor (as Paella does right now) is a bit irritating. YouTube and Vimeo do that as well:

![image](https://github.com/polimediaupv/paella-core/assets/7419664/f1b1070e-1661-4a79-a3de-a68ef91de675)

![image](https://github.com/polimediaupv/paella-core/assets/7419664/57f00ca9-954b-4088-b00c-5b540e189b2d)

I opened this issue on this core repository as I would argue this should be the case for every theme, and not just part of the new Openast design, for example.

**Comment by ferserc1** [comment]
Any aspect related to CSS can be modified in the player implementation:

https://paellaplayer.upv.es/#/doc/progress_indicator_customization.md

How to load custom style sheets is explained here:

https://paellaplayer.upv.es/#/doc/styles.md
