### ISSUE TITLE
In Chrome, loading problematic videos causes inconsistency in play/pause and volume/mute icons, and timeline text rendering

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella-core#344]
**Issue**: in `Chrome browser on MacOSX` on video load, in some videos, about 90% of the time when they load, Chrome only renders innerHTML() changes on every other change. In-between, it renders the innerHTML() DOM change as blank or empty. This causes the timeline text to flash as it toggles between rendering text and empty on every timeupdate. This also causes the play/pause button icon to toggle from an icon to empty on every click and the volume mute icon to toggle between empty and icon.

The issue immediately resolves itself when some item in the DOM gets a style change. For example, when changing to fullscreen and back, or hiding the control bar and revealing it again, Chrome begins to render the DOM innerHTML() changes properly.

Our site **resolved** this issue by showing the `showHandler` in the `progressIndicator` configuration of our Paella7 configuration file. The showHandler gets a style change on every timeupdate. This style update nudge solves Chrome's inconsistency in rendering the DOM innerHTML() changes.

The issue might only affect our site because we have problematic videos. The issue does not happen on all our videos, but appears to be on videos that have evidence of HLS.js nudge/error handling during the load.

This only happens in Chrome, not Safari or Firefox. I've only tested on MacOSX lapbook. Chrome hardware acceleration and all Chrome extensions were disabled.

**Comment by karendolan** [comment]
Screen shots examples of un-rendered but existing DOM innerHTML elements in the control bar:

<img width="400" alt="Screenshot 2023-10-24 at 9 30 17 AM" src="https://github.com/polimediaupv/paella-core/assets/1331728/cd6688c9-a8ea-41b0-a61e-f06a3003aac0" >

*Example of missing play/pause volume/mute and timeline text*

<img width="400" alt="Screenshot 2023-10-24 at 9 30 01 AM" src="https://github.com/polimediaupv/paella-core/assets/1331728/62c98736-1d3a-474d-81bd-eb0d7b51bb0f">

*Example of missing play icon toggled to view and volume toggled to view and missing timeline text*

<img width="400" alt="Screenshot 2023-10-24 at 9 29 50 AM" src="https://github.com/polimediaupv/paella-core/assets/1331728/2b4a6a45-e21c-42e5-b07e-0f9153a6f074">

*Example of missing play/pause icon and timeline text flashing into view on a timeupdate*

**Comment by ferserc1** [comment]
Can you send a link to one of these problematic videos?

I don't feel very comfortable adding such a fix, I would prefer to investigate the bug further to see if I can fix it at source, within the plugin itself that handles HLS streams.

**Comment by karendolan** [comment]
@ferserc1 that sounds great. The issue is where there is an `element.innerHTML` change and no companion `element.style` change. These areas:
https://github.com/polimediaupv/paella-core/blob/main/src/js/core/ProgressIndicator.js#L50
https://github.com/polimediaupv/paella-core/blob/main/src/js/core/ProgressIndicatorTimer.js#L12-L28

I will start a test server and undo our hack patch (that force a css change) in order for you to see the issue. I send the link directly to you in an email.

**Comment by karendolan** [comment]
> I will start a test server and undo our hack patch (that force a css change) in order for you to see the issue. I send the link directly to you in an email.

Hi @ferserc1, I could not reproduce the issue after removing our hack style update patch last week. After a lot of research, the issue seems related to Chrome's flurry of fall 2023 security patches around the use of "innerHTML". In summary, there is a lot of overhead, security checks, continual patches around the use of "innerHTML"  and it's "parseHTMLUnsafe" sub process.

The take-away for me it that when setting flat text on a node, it is less problematic, costly, and issue prone, to use "innerText" than "innerHTML".
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

**Comment by ferserc1** [comment]
Hi @karendolan. 

I have tried to reproduce this problem but have not been able to, so taking into account your last comment, I will close this issue. If necessary it will be reopened, in case we identify the problem.
