### ISSUE TITLE
Feature Request: Highlight nav slide that falls in the current timeline

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella-core#345]
This is a feature request. When the nav slides are shown, highlight the nav slide that falls in the current time. I believe this was a feature in the old Paella6. The use case is that it helps to orient the user to slides that are before and after the current segment block.

Also the slide button margin top needs defintion for the tab highlight to show all around a nav slide.

https://github.com/polimediaupv/paella-core/blob/main/src/js/core/TimeLinePopUp.js
Something like this...
![Screenshot 2023-11-01 at 1 56 37 PM](https://github.com/polimediaupv/paella-core/assets/1331728/a4af55a3-8aec-4178-9408-8f2b41993d81)

**Comment by ferserc1** [comment]
The plugin you are referring to is es.upv.paella.frameControlPlugin. It's fixed on version 1.41.4:

<img width="789" alt="image" src="https://github.com/polimediaupv/paella-core/assets/7019720/d23f1a8d-8b82-4840-91be-4b512cb5c489">

Make sure you have the latest version of paella-slide-plugins updated.

**Comment by karendolan** [comment]
Thanks! I was on 1.41.1
