### ISSUE TITLE
PLAYBACK_RATE_CHANGED event is not getting triggered

### ISSUE THREAD

**Issue by mliradelc** [polimediaupv/paella-core#61]
Hi,

I just found a possible bug, the event `PLABACK_RATE_CHANGED` is not getting triggered when the user changes the playback rate, instead the `SHOW_POPUP` gets triggered (That is ok, because you need to open a column to select your desired playback rate). but not the playback rate event.

**Comment by ferserc1** [comment]
The event is triggered correctly. You can test it from the javascript debug console:

```js
// Assuming the first paella core instance is loaded and ready:
__paella_instances__[0].bindEvent(__paella_instances__[0].Events.PLAYBACK_RATE_CHANGED, () => console.log("pb rate changed"))

// Then you can manually change the playback rate with the following line:
await __paella_instances__[0].videoContainer.setPlaybackRate(0.75)
```

If you have encountered a case where the event is not sent, please attach an example.

Did you mean that the user tracking plugin ([paella-user-tracking](https://github.com/polimediaupv/paella-user-tracking)) does not have the PLAYBACK_RATE_CHANGED event defined? In that case, please make sure to submit issues to the correct repository following the [contribution guidelines](https://paellaplayer.upv.es/#/contributions) at the paella player website.

**Comment by mliradelc** [comment]
Hi @ferserc1 thanks to look into this.

The bug is not inside the `paella-user-tracking` plugin, but in `paella-core`, I figure out when I was developing the Matomo plugin, It does not trigger the playback rate change. 

I realize that @miesgre  has updated user tracking. I will check it out.

**Comment by ferserc1** [comment]
I'm sorry, but paella-core IS triggering the event. You can check it even in the paellaplayer.upv.es website:

- Enter the main page
- Open the JavaScript terminal
- Type the following code to register the event

```js
__paella_instances__[0].bindEvent(__paella_instances__[0].Events.PLAYBACK_RATE_CHANGED, () => console.log("pb rate changed")) 
```

- Play the video, set another playback rate an see the development console
