### ISSUE TITLE
Support strict content security policies (CSP) via nonce or external CSS

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#74]
Hi there!

Ideally every website should set the `Content-Security-Policy` header as strictly as possible. One thing that's very beneficial to disallow is inline scripts and inline styles. It makes carrying out XSS attacks much more difficult. 

Unfortunately, when including Paella (via npm package), it is necessary to enable `style-src: 'unsafe-inline'` as otherwise, the CSS/styles applied by Paella are blocked. To improve overall website security, it would be great if Paella could somehow work in these situations. I see two options:

- Put all CSS in an external style sheet, include that in the NPM package and let the website serve this under some path. That path has to be configurable then of course. That way, the CSS falls under `style-src: 'self'` which is much safer to enable (basically the safest). (This solution is used by [plyr](https://github.com/sampotts/plyr), for example)

- Allow passing a nonce to Paella that is then used for all CSS. It is possible to say `style-src: 'nonce-6e2f321f36'` and then all inline CSS blocks that are somehow annotated with `nonce="6e2f321f36"` are allowed. It's not as good as serving the CSS as simple file, but assuming the attacker cannot inject JS, it makes things a lot safer than allowing `unsafe-inline`. (This solution is used by [emotion-js](https://emotion.sh/docs/@emotion/cache#nonce), for example)

**Comment by LukasKalbertodt** [comment]
> Would it be possible to provide the CSS files additionally and have the programmer who wants to restrict the Content-Security-Policy to include them manually?

I think this would work. This is how the Plyr player does it, kind of, I think.

> Apart from that, this solution also depends on all plugins developed for paella-core generating their own CSS files, which would also have to be included manually in HTML, is this correct?

I think so, yes. Or with the nonce-solution, paella-core could pass the nonce to all plugins.

**Comment by ferserc1** [comment]
Solving this problem with the current building system is extremely complex:

- Webpack is meant to package everything in a javascript file.
- There are ways around this to generate separate CSS files, but I'm having a lot of compatibility issues with other Webpack plugins. The best I've managed to do has generated a conflict with the sourcemap files that I haven't been able to solve.
- We are thinking about changing the building system in paella-core 2.x, so I don't see any interest in moving forward on this issue as long as we use webpack.

I'll take up this issue in version 2, and we'll take this issue into account when selecting the building system.

**Comment by LukasKalbertodt** [comment]
Sounds like a plan. It's unfortunate that paella-core 1.x will still require 'unsafe-inline', but I already suspected it would be a complex change.

**Comment by ferserc1** [comment]
This problem is solved in paella-core 2.0 as webpack is no longer needed.
