### ISSUE TITLE
Add some "unload" or "uninitialize" method

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#9]
In SPAs (e.g. using React), one would like to "unload" a Paella instance. Consider this:

- User visits a page
- My application renders a div
- My application initialized Paella with that div: Paella adds content to that div and does other stuff.
- User clicks on a link to get to another page. Due to this being a SPA, routing is done via JS, so the page change does not trigger a browser page reload. So everything that the Paella initialization did is still there.

Unloading Paella is necessary for two things:

- Clearing the content of the `div` so that it's empty, like it was before the initialization. Sure, I can do `div.textContent = ""` at the appropriate time, but (a) that's not super nice and (b) I'm not sure if Paella does anything else with that `div`.
- Unregistering event handlers and the like. This is to prevent memory leak. I don't know whether Paella makes use of event handlers, `setInterval` or anything like that. But if it does, there should be a way to instruct Paella to clean all that up.

**Comment by ferserc1** [comment]
Done!

See this document to know more about Paella Player life cycle: how to load and unload the player. This should work on SPA applications. I have tested in a simple svelte application that can change the video id without reload the page.

[https://github.com/polimediaupv/paella-core/blob/main/doc/life_cycle.md](https://github.com/polimediaupv/paella-core/blob/main/doc/life_cycle.md)
